config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"

  get '/about', to: 'static#about'

  resources :sessions, only: [:new, :create, :destroy]
  resources :user_accounts, only: [:new, :create]
  resources :username_reset, only: [:index]
  resources :password_reset, only: [:index]

  resources :dashboard, only: [:index]
  resources :drinks, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :support, only: [:index]

  get '*path' => redirect('/')
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/controllers/user_accounts_controller.rb
class UserAccountsController < ApplicationController
  def new; end

  def create
    new_user = User.new(user_params)
    if new_user.valid?
      new_user.save!
      if params[:password] == params[:password_confirmation]
        new_account = Account.new(
          user_id: new_user.id,
          role_id: 1,
          username: params[:username],
          password: params[:password]
        )
        if new_account.valid?
          new_account.save!
          flash[:success] = 'Account created successfully.'
          redirect_to root_path
        else
          new_user.destroy!
          flash[:error] = new_account.errors.full_messages.to_sentence + '.'
          redirect_to new_user_account_path
        end
      else
        new_user.destroy!
        flash[:error] = 'These passwords do not match.'
        redirect_to new_user_account_path
      end
    else
      flash[:error] = new_user.errors.full_messages.to_sentence + '.'
      redirect_to new_user_account_path
    end
  end

  private

  def user_params
    params
      .permit(:first_name, :last_name, :email, :phone_number)
  end
end

app/helpers/user_accounts_helper.rb
module UserAccountsHelper
end

app/views/user_accounts/new.html.erb
<%= render partial: "shared/main_logo" %>

<div class="new_user_container">
  <h2> Create Account </h2>
  <%= form_with url: user_accounts_path, method: :post, data: {turbo: false} do |form| %>

    <span class="red">*</span>
    <%= form.label :first_name, "First Name:" %>
    <%= form.text_field :first_name %>

    <span class="red">*</span>
    <%= form.label :last_name, "Last Name:" %>
    <%= form.text_field :last_name %>

    <span class="red">*</span>
    <%= form.label :email, "Email:" %>
    <%= form.text_field :email %>

    <span class="red">*</span>
    <%= form.label :phone_number, "Phone Number:" %>
    <%= form.text_field :phone_number %>

    <span class="red">*</span>
    <%= form.label :username, "Username:" %>
    <%= form.text_field :username %>

    <span class="red">*</span>
    <%= form.label :password, "Password:" %>
    <%= form.password_field :password %>

    <span class="red">*</span>
    <%= form.label :password_confirmation, "Password Confirmation:" %>
    <%= form.password_field :password_confirmation %>

    <%= form.submit "Create Account" %>
  <% end %>

  <p> <span class="red">*</span> Indicates a required field </p>

  <p> Note: Password must be at least 8 characters long, contain one uppercase letter, one lowercase letter, and one special character. </p>
</div>