config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"

  get '/about', to: 'static#about'

  resources :sessions, only: [:new, :create, :destroy]
  resources :user_accounts, only: [:new, :create]
  resources :username_reset, only: [:index]
  resources :password_reset, only: [:index]

  resources :dashboard, only: [:index]
  resources :drinks, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :support, only: [:index]

  get '*path' => redirect('/')
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/drink.rb
class Drink < ApplicationRecord
  validates :account_id, presence: true, numericality: true
  validates :drink_type, presence: true
  validates :ounces, presence: true, numericality: true
  validates :percentage, presence: true, numericality: true

  belongs_to :account

  def formatted_created_at
    created_at.strftime('%A, %B %-d, %Y @ %l:%M%P %Z')
  end

  def units
    ((percentage.to_f * (ounces.to_f * 29.5735)) / 1000).round(2)
  end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :require_user

  def index; end

  def new; end

  def create
    new_drink = current_user.drinks.new(drink_params)
    if new_drink.valid?
      new_drink.save!
      flash[:success] = 'Drink added successfully'
      redirect_to dashboard_index_path
    else
      flash[:error] = new_drink.errors.full_messages.to_sentence + '.'
      redirect_to new_drink_path
    end
  end

  def edit
    drink_id = params[:id].to_i
    @updated_drink = Drink.find(drink_id)
  end

  def update
    drink_id = params[:id].to_i
    updated_drink = Drink.find(drink_id)
    updated_drink.update!(drink_params)
    flash[:success] = 'Drink updated successfully'
    redirect_to drinks_path
  end

  def destroy
    drink_id = params[:id].to_i
    deleted_drink = Drink.find(drink_id)
    deleted_drink.destroy
    flash[:success] = 'Drink deleted successfully'
    redirect_to drinks_path
  end

  private

  def drink_params
    params
      .permit(:drink_type, :ounces, :percentage)
  end

  def require_user
    redirect_to root_path unless logged_in?
  end
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/views/drinks/edit.html.erb
<%= render partial: "shared/main_nav" %>

<div class="page_content">
  <h2> Update Drink </h2>

  <div class="edit_drink_input">
    <%= form_with url: drink_path(@updated_drink), method: :patch, data: {turbo: false} do |form| %>
      <%= form.label :drink_type, "Drink Type:" %>
      <%= form.select :drink_type, ['Beer', 'Wine', 'Spirit', 'Seltzer', 'Cider', 'Other'], selected: @updated_drink.drink_type, class: "form-control" %> <br><br>

      <%= form.label :ounces, "Ounces:" %>
      <%= form.text_field :ounces, inputmode: 'numeric', value: @updated_drink.ounces %>

      <%= form.label :percentage, "ABV Percentage:" %>
      <%= form.text_field :percentage, inputmode: 'numeric', value: @updated_drink.percentage %>

      <%= form.submit "Update Drink" %>
    <% end %>
  </div>
</div>

app/views/drinks/index.html.erb
<%= render partial: "shared/main_nav" %>

<div class="page_content">
  <h2> All Drinks (<%= current_user.drink_count_all_time %>)</h2>

  <% if current_user.drinks.empty? %>
    <p> There are currently no drinks. </p>
  <% else %>
    <% current_user.all_drinks_in_reverse_order.each do |drink| %>
      <div class="drink_<%= drink.id %> drink">
        <p> Type: <%= drink.drink_type %> </p>
        <p> Ounces: <%= drink.ounces %> </p>
        <p> ABV%: <%= drink.percentage %> </p>
        <p> Units: <%= drink.units %> </p>
        <p> Created: <%= drink.formatted_created_at %> </p>
        <p class='delete_drink'> <%= link_to 'Delete Drink', drink_path(drink), data: {turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this drink?'}, class: 'delete_drink' %> </p>
        <p class='update_drink'> <%= link_to 'Update Drink', edit_drink_path(drink), class: 'update_drink' %> </p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/drinks/new.html.erb
<%= render partial: "shared/main_nav" %>

<div class="page_content">
  <h2> Add a Drink </h2>

  <div class="new_drink_input">
    <%= form_with url: drinks_path, method: :post, data: {turbo: false} do |form| %>
      <%= form.label :drink_type, "Drink Type:" %>  
      <%= form.select :drink_type, ['Beer', 'Wine', 'Spirit', 'Seltzer', 'Cider', 'Other'], selected: 'Beer', class: "form-control" %> <br><br>

      <%= form.label :ounces, "Ounces:" %>
      <%= form.text_field :ounces, inputmode: 'numeric' %>

      <%= form.label :percentage, "ABV Percentage:" %>
      <%= form.text_field :percentage, inputmode: 'numeric' %>

      <%= form.submit "Add Drink" %>
    <% end %>
  </div>
</div>